# Generated by Django 3.2.6 on 2021-08-13 09:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedPlasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('person_email', models.CharField(default='', max_length=50)),
                ('file_field', models.FileField(upload_to='needPlasma/')),
                ('person_mobileNumber', models.CharField(default='', max_length=12)),
                ('person_age', models.IntegerField(default=0)),
                ('person_address', models.CharField(max_length=200)),
                ('person_gender', models.CharField(max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonatePlasma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('person_email', models.CharField(default='', max_length=50)),
                ('person_mobileNumber', models.CharField(default='', max_length=12)),
                ('person_age', models.IntegerField(default=0)),
                ('person_address', models.CharField(max_length=200)),
                ('date_last_tested_negative', models.DateField(verbose_name='Date Last Tested Negative for COVID19 ')),
                ('last_covid_report', models.FileField(upload_to='donatePlasma/')),
                ('igg_report', models.FileField(upload_to='donatePlasma/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
