# Generated by Django 3.2.6 on 2021-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0002_doctor_timingslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='timingSlots',
        ),
        migrations.AddField(
            model_name='doctor',
            name='timeslots',
            field=models.ManyToManyField(blank=True, default=None, to='doctorconsult.timeSlot'),
        ),
    ]
