# Generated by Django 3.2.6 on 2021-08-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0004_auto_20210815_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='timeslots',
            field=models.ManyToManyField(to='doctorconsult.timeSlot', verbose_name='Properties'),
        ),
    ]
