# Generated by Django 3.2.6 on 2021-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0005_auto_20210815_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
        ),
        migrations.DeleteModel(
            name='timeSlot',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='timeslots',
            field=models.ManyToManyField(to='doctorconsult.Property', verbose_name='Properties'),
        ),
    ]
