# Generated by Django 3.2.6 on 2021-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0006_auto_20210815_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='timeslots',
            field=models.ManyToManyField(to='doctorconsult.Property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
