# Generated by Django 3.2.6 on 2021-08-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0007_auto_20210815_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
