# Generated by Django 3.2.6 on 2021-08-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0008_doctor_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='file_field',
            new_name='profile_pic',
        ),
    ]
