# Generated by Django 3.2.6 on 2021-08-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorconsult', '0009_rename_file_field_doctor_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='address_of_your_workplace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
